export const TICTACTOE_TYPE = {
    SET_TIC_TAC_TOE_CELLS : "SET_TIC_TAC_TOE_CELLS",
    SET_PLAYER1_SCORE: "SET_PLAYER1_SCORE",
    SET_PLAYER2_SCORE: "SET_PLAYER2_SCORE",
    SET_GAME_MESSAGE: "SET_GAME_MESSAGE",
    SET_COMP_ENABLED: "SET_COMP_ENABLED",
    SET_CURRENT_PLAYER: "SET_CURRENT_PLAYER",
    RESET_TICTACTOEGAME: "RESET_TICTACTOEGAME",
    SET_GAME_OVER: "SET_GAME_OVER",
    SET_WIN_INDEX: "SET_WIN_INDEX",
    DECREMENT_NUMBER_OF_TURNS: "DECREMENT_NUMBER_OF_TURNS",
    SET_TIE_TRUE: "SET_TIE_TRUE",
    PICK_PLAYER_TYPE: "PICK_PLAYER_TYPE",
    UPDATE_CURRENT_POSITIONS: "UPDATE_CURRENT_POSITIONS",
    UPDATE_POSSIBLE_WIN_COMBO: "UPDATE_POSSIBLE_WIN_COMBO"
};