export const GAMES_TYPE = {
    SET_PLAYER1_SCORE: "SET_PLAYER1_SCORE",
    SET_PLAYER2_SCORE: "SET_PLAYER2_SCORE",
    SET_GAME_MESSAGE: "SET_GAME_MESSAGE",
    SET_COMP_ENABLED: "SET_COMP_ENABLED",
    SET_CURRENT_PLAYER: "SET_CURRENT_PLAYER",
    SET_GAME_OVER: "SET_GAME_OVER",
    PICK_PLAYER_TYPE: "PICK_PLAYER_TYPE",
    SET_TIE_TRUE: "SET_TIE_TRUE",
    RESET_GAME: "RESET_GAME"
};

export const TICTACTOE_TYPE = {
    SET_TIC_TAC_TOE_CELLS : "SET_TIC_TAC_TOE_CELLS", 
    RESET_TICTACTOEGAME: "RESET_TICTACTOEGAME",
    SET_WIN_INDEX: "SET_WIN_INDEX",
    DECREMENT_NUMBER_OF_TURNS: "DECREMENT_NUMBER_OF_TURNS",
    UPDATE_CURRENT_POSITIONS: "UPDATE_CURRENT_POSITIONS",
    UPDATE_POSSIBLE_WIN_COMBO: "UPDATE_POSSIBLE_WIN_COMBO",
    UPDATE_PLAYER_ONE_POSSIBLE_WIN_COMBO: "UPDATE_PLAYER_ONE_POSSIBLE_WIN_COMBO",
    UPDATE_NEXT_MOVE: "UPDATE_NEXT_MOVE",
    UPDATE_INDEX_POSSIBLE_WIN: "UPDATE_INDEX_POSSIBLE_WIN"
};

export const CONNECTFOUR_TYPE = {
    SET_CONNECT_FOUR_TABLE : "SET_CONNECT_FOUR_TABLE",
    RESET_CONNECT_FOUR_GAME: "RESET_CONNECT_FOUR_GAME",
};