export const TICTACTOE_TYPE = {
    SET_TIC_TAC_TOE_CELLS : "SET_TIC_TAC_TOE_CELLS",
    SET_PLAYER1_SCORE: "SET_PLAYER1_SCORE",
    SET_PLAYER2_SCORE: "SET_PLAYER2_SCORE",
    SET_GAME_MESSAGE: "SET_GAME_MESSAGE",
    SET_COMP_ENABLED: "SET_COMP_ENABLED"
};